### ISSUE TITLE
Yarn versions require different lockfiles

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1384]
In yarn `1.12.0`, [the integrity field was removed from the `yarn.lock` file](https://github.com/yarnpkg/yarn/blob/master/CHANGELOG.md#1120). So if devs are on various versions of yarn it could produce thrashing in the lockfile as integrity is added and removed by each respectively.

Yarn allows the [path to be defined](https://yarnpkg.com/en/docs/yarnrc#yarn-path-) which in turn allows us to check a yarn binary into the repo and use that specific version. This would ensure that all devs are using the same version of yarn.

- [x] Upgrade `yarn`
- [x] Install `yarn` as a project `devDependency`
- [x] Create a `.yarnrc` file that defines the path to the local `yarn` binary
- [x] Change the CI yarn install command to `yarn install --frozen-lockfile`

**Comment by benjamincharity** [comment]
Problem: We recently hit an issue where version A of yarn formats `yarn.lock` file differently than version B of yarn which causes some thrashing if different engineers are working with different versions yarn installed locally.

Yarn allows us to define the path to the yarn binary that should be used. This allows us to check a specific version of yarn in as a devDependency and then point yarn to use that one using a `.yarnrc` file. This did solve the version issue across machines.

While that solves the issue locally, it creates an issue when running on CircleCI. This however causes yarn to fail on CI as it can’t find yarn. This seems to happen even when restoring `node_modules` from the cache.

CI error:

```
#!/bin/bash -eo pipefail
yarn install
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '/home/circleci/ci-build/bin/yarn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
Exited with code 1
```

I thought that since we restore the `node_modules` directory that Circle would find it and use it. But it doesn’t seem to work. So I’ve been looking through random repos and it seems that many people who use this flag actually check yarn in as an actual file. So then yarn never needs to be installed - it’s already in your repo.

Currently the pain-point of a thrashing `yarn.lock` file is not so great that checking in the actual yarn binary feels like the correct path.

Closing until something changes or new information is found.
