### ISSUE TITLE
CI: Need to build AoT app that consumes the library

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#746]
The current release process does not catch AoT build errors. We need to be verifying this integration before releases.

- [ ] Build AoT version of demo app during CI
  - Running `ng build --aot --prod` should throw a hard failure if not working

---

Currently running into this error:

```
Cannot read property 'isSupported' of undefined
TypeError: Cannot read property 'isSupported' of undefined
    at NgCliWebpackConfig.addTargetDefaults (/home/circleci/ci-build/node_modules/@angular/cli/models/webpack-config.js:91:52)
    at new NgCliWebpackConfig (/home/circleci/ci-build/node_modules/@angular/cli/models/webpack-config.js:16:29)
    at Class.run (/home/circleci/ci-build/node_modules/@angular/cli/tasks/build.js:31:31)
    at Class.run (/home/circleci/ci-build/node_modules/@angular/cli/commands/build.js:250:40)
    at resolve (/home/circleci/ci-build/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (/home/circleci/ci-build/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/home/circleci/ci-build/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```
https://circleci.com/gh/GetTerminus/terminus-ui/1920

Build works fine locally.

**Comment by benjamincharity** [comment]
Blocked by error `Cannot read property 'isSupported' of undefined`: https://circleci.com/gh/GetTerminus/terminus-ui/1946
